### ISSUE TITLE
Example with javascript client

### ISSUE THREAD

**Issue by wokawaka** [RainwayApp/spitfire#13]
I wish for there to be a simple javascript example where I can connect the a javascript client to the .net code. As it is now I find it very hard to figure out how to use the library. Id be willing to make a donation towards this cause.

**Comment by wokawaka** [comment]
I'm quite serious about the above offer. If someone can point me to a repo where a javascript client can connect to a C# "server" over the internet through a NAT (not just localhost) and send something over udp using the datachannel I will send them 50$ through paypal.

**Comment by Terricide** [comment]
Are you adding stun and/or turn servers on both the javascript and c# side and do you see both sides passing ice messages with their external pubkic ip address?

**Comment by wokawaka** [comment]
@Codeusa Thank you. Gotta say I really appreciate the work you guys have put into getting a C# client up and running. Just a bit confusing to understand whats going on when you don't completely grasp webrtc to begin with :)

**Comment by Terricide** [comment]
I think that is where a turn server would come in handy if it is not able to open the ports. However it adds latency and you need a turn server to handle the traffic
