### ISSUE TITLE
Fully fledged example?

### ISSUE THREAD

**Issue by glemselenselv** [RainwayApp/spitfire#21]
Hi, I just came across this repo yesterday and find it really interesting.
Somewhere in the example code it reads "TODO: fully fledged example"... is such an example available somewhere?

Basically I want to connect two console applications and exchange some data via an WebRtc data channel. Unfortunately I can't seem to get it working with Spitfire without some more guidance or how-to-use information.

Any help would be super awesome. Cheers!
~Killian

**Comment by Scraft** [comment]
+1

I am in the same position, I would like to connect to console applications. Ultimately I am trying to implement with Twilio (using their NAT Traversal), specifically I can get their ICE servers for STUN/TURN, and I wish to establish via those servers, but for now, I am happy to use the stun.l.google.com server in the source.

Right now I run the sample, on two machines, but nothing happens.

**Comment by glemselenselv** [comment]
Why has this been closed? No answer so far, no in-depth example, I'd really appreciate some advice.

**Comment by Codeusa** [comment]
We're porting the library to be .NET compatible so the API will change -- at that time the example will be updated.

**Comment by glemselenselv** [comment]
Thanks for the clarification. :)
