### ISSUE TITLE
Expose webrtc's native screen capture module

### ISSUE THREAD

**Issue by smedasn** [RainwayApp/spitfire#4]
There is a similar project here on github which exposes webrtc's native screen capture. Would love to see this feature in spitfire

Thx for the great lib btw!

**Comment by goldenyz** [comment]
> There is a similar project here on github which exposes webrtc's native screen capture. Would love to see this feature in spitfire
> 
> Thx for the great lib btw!

which project? I'm finding a library to do so for a long time...

**Comment by Codeusa** [comment]
We're happy to accept a pull request, but generally our focus is on the use of data channels which is how we transmit our media to peers.
