### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by Terricide** [RainwayApp/spitfire#9]
I have this library working great in windows 10. But when I tried Windows 7 I'm getting Badformatexception when using 32-bit and AccessViolations when using 64-bit.

I've download the source and compiled it on windows 7 using Visual Studio 2017 and it still does it when using the example project.

**Comment by Codeusa** [comment]
Can you see if installing .NET 4 on the system helps?

**Comment by Terricide** [comment]
Yeah it was installed. I actually installed visual studio 2017 on windows 7 and got those errors after compiling it on the machine.

**Comment by Terricide** [comment]
Sorry that was after I tried the nuget library first and tried both 32 bit and 64 bit.

**Comment by Terricide** [comment]
Hi I ended up fixing this myself if you are interested. I also modified the example to open a webrtc connection on a single machine to test.

**Comment by Codeusa** [comment]
Awesome @Terricide could you share the details on the fix?

**Comment by Terricide** [comment]
I think it is just an issue with it being a mixed c++/clr dll. I used https://github.com/radioman/WebRtc.NET/tree/staging branch as a starting point and turned spitfire.dll into a native dll and created a spitfire.net using pinvoke and it works great.

**Comment by Terricide** [comment]
I'll try and create a pull request next week

**Comment by Codeusa** [comment]
So we've been aware that P/INVOKE is a solution for awhile, it just doesn't fit with our usage. It is good you got it working nonetheless. I'm just curious what the actual issue is.

**Comment by Terricide** [comment]
It's strange because it just seems to break before it does anything. What is the reason for not wanting pinvoke? It seems to be working great and I'm thinking linux and mac should be much easier as well.

**Comment by Terricide** [comment]
I created the pull request if you want to take a look. I also added a single process example creating a data channel and passing a hello world message.

**Comment by Terricide** [comment]
I just did some tweaks to get 64-bit working

**Comment by radioman** [comment]
...actually solution for win7/xp was https://github.com/radioman/WebRtc.NET/commit/9afe865b03e41faaa6aecf90ff200a413ee487b7

https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization

**Comment by Codeusa** [comment]
That makes sense. @healingbrew could you try implementing the above fix (disabling thread-safe statics) from @radioman in our build of WebRTC and the Spitfire library? Fixing this library on Windows XP/7 would help with further .NET adoption.

**Comment by Terricide** [comment]
Yeah that makes sense. My solution didn't actually work and I figured out how to debug it and ProcessMessages is throwing the exception but when I step through code it doesn't always do it.

**Comment by healingbrew** [comment]
Will do once I get around to it (shouldn't be too long, don't worry!)

**Comment by Terricide** [comment]
FYI I'm using the build scripts from this repo "https://github.com/sourcey/webrtc-builds" to build the library and so far it is working pretty good.

**Comment by Terricide** [comment]
I was compiling against the latest webrtc version and I found this.

To build WebRTC with DataChannel support only:

// Create a peerconnection factory without media support.
CreateModularPeerConnectionFactory(network_thread, 
				      worker_thread, 
				      signaling_thread,
				      nullptr /*MediaEngineInterface*/,
				      nullptr /*CallFactoryInterface*/,
				      nullptr /*RtcEventLogFactoryInterface/);

So you shouldn't need all the fake audio video factories

**Comment by Codeusa** [comment]
The fake factories were required to address a bug still present in WebRTC which is even when you build for data channels only if there is an audio device that has its sample rate too high it crashes.

**Comment by Terricide** [comment]
I built the libraries here with threadsafeinit disabled.

https://github.com/Terricide/WebRtc.NET/tree/master/WebRtcNative/lib
